# Generated by Django 3.1.3 on 2020-11-14 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portion', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('date', models.DateField(auto_now=True)),
                ('large_group', models.TextField()),
                ('small_group', models.TextField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('art', models.TextField(blank=True, null=True)),
                ('music', models.TextField(blank=True, null=True)),
                ('needed_items', models.TextField()),
                ('centers', models.ManyToManyField(related_name='reports', to='center.Center')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='family.child')),
                ('meals', models.ManyToManyField(related_name='reports', to='center.Meal')),
            ],
        ),
    ]
