# Generated by Django 3.1.3 on 2020-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_dailyreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
